# Generated by Django 5.1.1 on 2024-01-01 00:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('parameter_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('enum', 'Enumeration')], max_length=20, verbose_name='Parameter Type')),
                ('default_value', models.TextField(blank=True, verbose_name='Default Value')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min Value')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max Value')),
                ('allowed_values', models.JSONField(blank=True, default=list, verbose_name='Allowed Values')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='Is Readonly')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('help_text', models.TextField(blank=True, verbose_name='Help Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='device_config.devicetype', verbose_name='Device Type')),
            ],
            options={
                'verbose_name': 'Device Parameter',
                'verbose_name_plural': 'Device Parameters',
                'ordering': ['order', 'name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='Device ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('config_data', models.JSONField(default=dict, verbose_name='Configuration Data')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_device_configs', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='device_config.devicetype', verbose_name='Device Type')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
                'ordering': ['-created_at'],
                'unique_together': {('device_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('synced', 'Synced')], max_length=20, verbose_name='Action')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Old Values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='New Values')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Changed Fields')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='device_config.deviceconfiguration', verbose_name='Device Configuration')),
            ],
            options={
                'verbose_name': 'Device Configuration History',
                'verbose_name_plural': 'Device Configuration History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('timeout', 'Timeout')], max_length=20, verbose_name='Sync Status')),
                ('sync_started', models.DateTimeField(auto_now_add=True, verbose_name='Sync Started')),
                ('sync_completed', models.DateTimeField(blank=True, null=True, verbose_name='Sync Completed')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('data_sent', models.JSONField(blank=True, default=dict, verbose_name='Data Sent')),
                ('data_received', models.JSONField(blank=True, default=dict, verbose_name='Data Received')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Device IP')),
                ('device_version', models.CharField(blank=True, max_length=50, verbose_name='Device Version')),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='device_config.deviceconfiguration', verbose_name='Device Configuration')),
            ],
            options={
                'verbose_name': 'Device Sync Log',
                'verbose_name_plural': 'Device Sync Logs',
                'ordering': ['-sync_started'],
            },
        ),
    ]
